### ISSUE TITLE
Create MARKET contract reverse lookup by address

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/Dapp#10]
Currently we have a contract explorer that allows users to find a white listed MARKET contract with searchable fields.  However we need to create a page that allows a user to enter in a contract address and retrieve the contract specs and if it is a white listed (valid) contract.

**Comment by cryptomental** [comment]
I may be able to implement this one. Let me give it a try.

**Comment by cryptomental** [comment]
Closing as the PR was merged ;-)
