### ISSUE TITLE
[Deployment] Setup automated deployment of dApp to AWS

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/dApp#100]

**Comment by pelsasser** [comment]
@eswarasai can you coordinate with @pchuck on deployment of the dApp in the coming days

**Comment by eswarasai** [comment]
@pelsasser -- Sure Phil. I've touch based with @pchuck yesterday. Need to have a clear strategy if development for serverless architecture. I'll update here once I have it devised.
