### ISSUE TITLE
[General] Add templates for issues and PRs

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#103]

**Comment by eswarasai** [comment]
@pelsasser -- Initial templates are in place. Let me know if this is good to close

**Comment by pelsasser** [comment]
@eswarasai thanks! maybe we should wait until we have contribution guidelines to close the issue so we can link them in the template?

**Comment by eswarasai** [comment]
@pelsasser -- What's still pending here? I think the contribution guidelines PR is merged as well right?

cc: @pchuck

**Comment by pelsasser** [comment]
closing!
