### ISSUE TITLE
Add Node version information to readme and package.json

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#121]

**Comment by perfectmak** [comment]
For this task, should we just add the latest stable Node version that currently works or we should find the minimum version that still works for the codebase?

**Comment by pelsasser** [comment]
That is a great question.  I personally haven't tested > 8.11.1 so was really just calling that the version and moving forward for now.  Open to suggestions for sure.

**Comment by eswarasai** [comment]
It does make sense to recommend the LTS version of the NodeJS as part of the package.json if everything works fine using that version

**Comment by I3uckwheat** [comment]
Sorry it took so long! Got distracted!
