### ISSUE TITLE
[Sim Exchange] Unit Tests

### ISSUE THREAD

**Issue by perfectmak** [MARKETProtocol/dApp#125]
### User Story
Although the SimExchange Component is currently not available, there has been quite some work already done on it.
We want these components to have proper unit tests in their current state.

### Why Is this Needed?
This is needed to improve the reliability of the codebase and also help increase coverage of the tests.
Also having tests for this components will also help new members of the community who are trying to understand the components functionalities.

### Definition of Done
This task would be done if you are able to increase the tests coverage for the SimExchange Components up to over 70% in a meaningful way.
These include the subcomponents, reducers, and actions that have to do with SimExchange. 

### Additional Information
Feel free to refactor the current codebase in the best way you feel would allow components to the testable. Afterall that is the purpose of our testing 🙂.

**Comment by ConnorChristie** [comment]
I can start adding tests to this component! And who knows, some bugs might be squashed as a result :)

**Comment by pelsasser** [comment]
@ConnorChristie awesome! thanks for getting involved!  Please let @eswarasai or I know if you need any help.
