### ISSUE TITLE
[Contract Deployer] modify `checkContract()` to confirm contract is ERC20

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#128]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature
We need to add a check to ensure that the address user for the `Base Token` in our deployments isn't just a smart contract address, but is in fact an ERC20

### Current Behavior
[comment]: # (Describe what actually happened.)
Checks only if a smart contract

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Checks to ensure it is an ERC20 compliant contract

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
- [ ]  modify `checkContract` to be `checkERC20Contract` and add needed code to modify function
- [ ] create additional testing to cover this code scenario
- [ ] modify error messaging to be more specific 

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by pelsasser** [comment]
@maektwain - I think this approach makes sense.  In the longer term we could create a whitelist of erc20 contracts we allow for collateral, but for the time being, I think validating them as you suggest is the only option.

**Comment by bakaoh** [comment]
I think we can use other service like etherscan (ex: https://etherscan.io/token/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0) instead of create a whitelist ourselves
Another approach can be found here https://ethereum.stackexchange.com/a/38400 using some simple check in bytecode with an acceptable accuracy

**Comment by bakaoh** [comment]
I tested it with some contracts (erc20 and not erc20) and it works. I'm on vacation without my laptop so i can't put the code here

**Comment by eswarasai** [comment]
@bakaoh -- Sure. No problem. Please raise a PR whenever you can get to it. Thanks :)
