### ISSUE TITLE
[Security] Potential Security Vulnerability warning from GitHub

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/dApp#130]
### Description
`hoek` node module before 5.0.3 suffers from a Modification of Assumed-Immutable Data (MAID) vulnerability via 'merge'

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Vulnerability

### Solution
`package-lock.json` update suggested: `hoek` ~> `5.0.3`

**Comment by I3uckwheat** [comment]
Isn't this related to jest and is only on the development build? Would this still be an issue on the production build?

**Comment by eswarasai** [comment]
@I3uckwheat -- I don't think it's just related to `jest` but yeah this is a warning from GitHub based on the dependencies in `package-lock.json` which is irrespective of development vs production build.

**Comment by travisdmathis** [comment]
@eswarasai this package doesn't exist in the dApp, it is in the protocol repo however.
