### ISSUE TITLE
[GasPriceField] Fix the console warning

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/dApp#131]
### Description

*Summary*: Fix the below console error for GasPriceField component

```
Warning: Can only update a mounted or mounting component.
This usually means you called setState, replaceState, or forceUpdate on an unmounted component.
This is a no-op.

Please check the code for the GasPriceField component.
```

### Reproduction

*Summary*: Can be reproduced either by deploying contract or submitting a test query.

**Comment by vikaskyadav** [comment]
@eswarasai  How can I clone this issue ? I think I can fix this.

**Comment by eswarasai** [comment]
@vikaskyadav -- Even I'm not sure of the exact steps, but if you keep playing around with the `dApp` like deploying contracts or test query, you should be able to see that error in the console.
