### ISSUE TITLE
Refining the Text in this image on Landing page

### ISSUE THREAD

**Issue by vikaskyadav** [MARKETProtocol/dApp#141]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: Doesn't look good as a part of dApp workflow.

### Description
![screenshot from 2018-05-04 15-12-03](https://user-images.githubusercontent.com/12607959/39625237-3958aa98-4fba-11e8-939f-141b8b310f44.png)

*Type*:  Bug

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
A refined image in place of the existing one with proper spacing between the word "Contract"

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Visit this link: <a href="http://marketprotocol.io/" target="_blank">http://marketprotocol.io </a>

**Comment by pelsasser** [comment]
closing this - related to website, not dApp. But also fixed in https://github.com/MARKETProtocol/website/commit/4230f6903791bdf9aa1e2ba7ca6674be02a2ceb0
