### ISSUE TITLE
[Welcome] Refine welcome message text 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#147]
### User Story

As a user I would like to see a nice welcome message with instructions for the dApp

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: To help with on boarding new users

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Welcome message needs some new text

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

Header - Welcome to the official MARKET Protocol dApp

Add Intstructions, with links to video tutorials, docs, and faucets

Remove cancel button

**Comment by iamonuwa** [comment]
@pelsasser can I pick this task?

**Comment by pelsasser** [comment]
@iamonuwa - you are more than welcome to take a crack at it, but I may need to help revise it as you go.  Would love the help! 

Here is a link to our youtube videos with a few tutorials -

https://www.youtube.com/channel/UCk9Yc59tC0VI5NV4HwY4lbg?view_as=subscriber

**Comment by iamonuwa** [comment]
Awesomeness

**Comment by pelsasser** [comment]
most of the text has been updated, I think only thing remaining is to remove the cancel button.

**Comment by eswarasai** [comment]
@pelsasser -- I can take care of removing the Cancel button. It's a small commit from my end. Let me add that right away and call it done 👍

**Comment by pelsasser** [comment]
closing this! thanks all.  @iamonuwa hope you pick up another issue here!
