### ISSUE TITLE
[main] Create new main page for our dApp!

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#168]
### User Story

As a user I want brand consistency! It makes me feel comfortable 

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: we want to tie in the dApp to the theme of our main site at marketprotocol.io

### Description

Here is the mock 
![market_dapp](https://user-images.githubusercontent.com/15096737/40447110-bac23a76-5e8e-11e8-8172-0edde2b610c4.png)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Using the [.sketch file](https://github.com/MARKETProtocol/assets/blob/master/MockUps/MARKET_Protocol-dApp.sketch) and the [.ai file](https://github.com/MARKETProtocol/assets/blob/master/MockUps/MARKET_Protocol-dApp-Graphics.ai) create the needed rebuild of the main page on the dApp.

A few important notes. 
1. Please use .svg graphic from the .ai file for high res images
1. The footer and "Join our newsletter" sections have already been created in the `website` repo and can be used as much as is possible.   
 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Implement provided design in React
- [ ] Must be fully responsive and use existing styled components wherever possible
- [ ] PR must include tests for all code created in order to be accepted.

**Comment by pelsasser** [comment]
@nitinrgupta has got this one.

**Comment by eswarasai** [comment]
@nitinrgupta -- Please find below list of UI concerns:
- Can we not use similar design from that of `website` for the newsletter subscription -- http://dev.website.marketprotocol.io/#subscribe?
- Footer nav menu has little padding compared to that of `website` footer. Can we try to match the UI with that of the `website`?
- In order for the footer to be visible, user has to scroll to the bottom of the page. Can we try to set height equal to that of the inner content and display footer right below it without wasting too much space on the screen? Ref: `/contract/find`
- Is it possible to have a responsive nav menu UI for the mobile device resolution similar to the `website`?
