### ISSUE TITLE
[Footer] Add Jobs page link to footer 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#204]
### Description

*Type*:  Feature

Copy the existing footer links from the [static site](https://marketprotocol.io) to the dApp

### Current Behavior
No jobs link in footer

### Expected Behavior
jobs link in footer

### Reproduction
see https://dapp.marketprotocol.io/

### Definition of Done

- [ ] Add new footer link
- [ ] Add / update test for all code written

**Comment by pelsasser** [comment]
@eswarasai - can you knock this out? figure its too small to really stake.

**Comment by eswarasai** [comment]
@pelsasser -- Sure Phil. On it 👍
