### ISSUE TITLE
[SimExchange] Display my fills and execution

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#214]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user i would like to be able to see all of my fills for a given MARKET Protocol smart contract.

### Why Is this Needed?
*Summary*: help users track their orders and positions and fills

### Description
*Type*: Feature

### Current Behavior
Users don't have any way of seeing their recent filled orders.

### Expected Behavior
Users are able to see their filled orders (and orders, but that is another issue)

### Solution
*Summary*: Create functionality to listen to the `OrderFilled` event and display a users fills (where they have acted as `taker` or `maker`)

We may need to expose some of this in MARKET.js  before finishing the scope here.

**Comment by travisdmathis** [comment]
duplicate
