### ISSUE TITLE
[Deployment Flow] Outstanding issues before release

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#231]
- Links to etherscan do not link to the correct rinkeby transactions
- Add text / remove lorem ipsum
- [Responsiveness] Possibly integrate market loader animation somewhere?
- Instead of deploying should it read something like "waiting for transaction to be mined..."

**Comment by travisdmathis** [comment]
taking this and working on it while I was for unblocking on other issues @pelsasser

**Comment by pelsasser** [comment]
Text

## MARKET Protocol Smart Contract Deployment
### Deploying your MarketContract
The MarketContract is the main contract responsible for facilitating many to many trading.  Your customized contract is about to be deployed to the Ethereum blockchain and will soon be tradeable!
### Adding your contract to our registry
We want other's to be able to find your awesome new contract, and are adding it to our registry so it will show up in the `Explore Contracts` page.  

## MARKET Protocol Collateral Pool Deployment
### Deploying a new Collateral Pool for your contract.
Each MARKET Protocol Smart Contract needs its own collateral pool to ensure that all trades are always 100% collateralized and solvent!
### Linking the Collateral Pool to your contract
Finally, we must link your newly deployed contracts together to ensure all functionality is in place.  Shortly, your contract will be all set for use.  Happy Trading!
