### ISSUE TITLE
Refactor existing market.js implementations to use the new MarketJS middleware

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/dApp#238]
### Why Is this Needed?
Clean up codebase and get it in line with the new work we are doing.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] All instantiations of `new Market()` should be moved to marketMiddleware.js

**Comment by eswarasai** [comment]
@travisdmathis -- I think we can close this right? 
Ref: https://github.com/MARKETProtocol/dApp/commit/80022403a2d6614fc74df01350ad4232336f06fa
