### ISSUE TITLE
[Design] Mock Trading UI 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#242]
### User Story
As a user, I would like to see one screen that encompasses all needed information for me to be able to make a trade using MARKET Protocol

### Why Is this Needed?
*Summary*: Better UI/UX

### Description
*Type*: Feature

### Solution

*Summary*: @nitinrgupta and @auregimon to mock up trading UI

### Definition of complete
- [x] Overall trading UI

### Additional Information
Reference for a nice example - https://app.radarrelay.com/ZRX/WETH

**Comment by nitinrgupta** [comment]
Draft of the UI based on Phil's 'wireframe' : https://zpl.io/VYBDrqM

**Comment by rojosnow** [comment]
@nitinrgupta I like the work you guys are doing! What are the next steps?

**Comment by rojosnow** [comment]
@nitinrgupta Cool.

**Comment by nitinrgupta** [comment]
Latest Iteration based on @pelsasser's feedback
![market dapp - exchange v6](https://user-images.githubusercontent.com/4952395/44208832-42e4a780-a17f-11e8-9ffb-057635d1e1c5.png)
