### ISSUE TITLE
[Deploy Contract UI/UX] Implement the new Gas settings design

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#243]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Implement the new design for Gas settings on the Simplified Deploy contracts flow

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: feature

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="546" alt="screen shot 2018-07-19 at 2 33 15 am" src="https://user-images.githubusercontent.com/4952395/42907661-1e1202e8-8afc-11e8-95b8-ad1412c2dcd8.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
<img width="549" alt="screen shot 2018-07-19 at 2 22 32 am" src="https://user-images.githubusercontent.com/4952395/42907669-24843e98-8afc-11e8-9897-0e5e300d83b6.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Any change on Gas price input field should reflect appropriately in the slider and vice-versa

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Part of #234 and `feature/deploy-contracts-redesign` branch

**Comment by nitinrgupta** [comment]
@pelsasser I've changed the implementation of the desing a bit based on the response of ethgasAPI and AntD component availability. I feel this should do. What are your thoughts on this?

<img width="584" alt="screen shot 2018-07-20 at 3 59 22 pm" src="https://user-images.githubusercontent.com/4952395/42997885-e8993088-8c35-11e8-97d9-4b042b30b7bf.png">

**Comment by pelsasser** [comment]
Is there any way to make the slider a big more prominent? If I saw this, I am not sure it is as clear to me I can drag the slider around as it is in the first mock. 

The <> on the slider in the first mock really also help in showing the user that this is possible.

**Comment by nitinrgupta** [comment]
Valid point @pelsasser! I'll see what I can do.

**Comment by nitinrgupta** [comment]
Modified the slider to look bit better with arrows
<img width="551" alt="screen shot 2018-07-23 at 2 04 00 pm" src="https://user-images.githubusercontent.com/4952395/43066090-546ce80c-8e81-11e8-8629-eaa006860dca.png">

**Comment by pelsasser** [comment]
@nitinrgupta - is there a reason the Medium isn't in the middle of the slider?

I assume we still need to work on the backend to decide the range of the slide / etc also correct?  Do you want to create an issue to track that?  We can bounty it if you like

**Comment by nitinrgupta** [comment]
@pelsasser this is due to the unequal difference between slow-medium and medium-fast values returned from the API.

Here's a sample API response we are using:
```sh
{
"average": 60,
"blockNum": 6015701,
"fast": 130,
"safeLow": 60,
"safeLowWait": 2.1,
"speed": 0.9952410140646821,
"fastestWait": 0.5,
"avgWait": 2.1,
"fastest": 400,
"block_time": 14.505102040816327,
"fastWait": 0.7
}
```

Right now the range is calculated by using the `safeLow` value as min and `fast` value as max returned from the API which should work correctly. These value change time to time and the difference between average/safeLow vs average/fast as well change which is why you see the Medium point not appearing in the center always.

**Comment by nitinrgupta** [comment]
@pelsasser let me know if the implementation sounds good.

**Comment by pelsasser** [comment]
@nitinrgupta got it.  I think its a little bit of an odd UX.

any reason not to just set the Medium to be in the middle of these 2 values?

**Comment by nitinrgupta** [comment]
We can do that, but that won't be the same value as what we are getting from the API. 

I'll just do that. We can use the 'average' value from the API to set as the default one and push the Medium text to the centre irrespective of its value. I'll quickly just do that.

**Comment by pelsasser** [comment]
@nitinrgupta - got it, I understand this a bit better now.  We could leave as is and just rename "Medium" to "Average" to avoid confusion as well?

**Comment by nitinrgupta** [comment]
@pelsasser made all the changes based on your feedback.
I'll leave it to you for closing this issue :)
