### ISSUE TITLE
[Deploy Contract UI/UX] Implement the new design for deploy contracts step

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#248]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Redesign the deploy contracts process based on the designs provided

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="593" alt="screen shot 2018-07-19 at 11 26 02 am" src="https://user-images.githubusercontent.com/4952395/42924173-8aa42fcc-8b46-11e8-9c88-6429f3825156.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
<img width="428" alt="screen shot 2018-07-19 at 11 24 40 am" src="https://user-images.githubusercontent.com/4952395/42924182-919458ac-8b46-11e8-9b3e-d463fd93089f.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
The deploy contract step should have a more simpler UI with minimal steps as shown in the given mockup

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Part of #234 and `feature/deploy-contracts-redesign` branch

**Comment by pelsasser** [comment]
@nitinrgupta - should we bounty this?

**Comment by nitinrgupta** [comment]
@pelsasser I've modified this UI and brought it to an improved stated that the current one.

Here's what it looks like now.
<img width="554" alt="screen shot 2018-07-23 at 2 42 11 pm" src="https://user-images.githubusercontent.com/4952395/43075884-d4a33e54-8e9f-11e8-84fb-4753790bd8f7.png">

<img width="495" alt="screen shot 2018-07-23 at 5 41 16 pm" src="https://user-images.githubusercontent.com/4952395/43075894-dbb4f4bc-8e9f-11e8-9cd9-1b54d3405174.png">

We can bounty the remaining change (The UI part to look like the one in designs) if necessary.
