### ISSUE TITLE
[Contract Explorer] Create grid view of contracts in explorer page

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#275]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Create a grid view to list all the contracts in `/contract/explorer` page. Provide user to switch between the grid view and tabular view. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Zeplin: https://zpl.io/bzW3NQG
<img width="1078" alt="screen shot 2018-07-30 at 10 05 49 pm" src="https://user-images.githubusercontent.com/4952395/43410523-c83c71b2-9444-11e8-83f7-f97f3514fb02.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
 - [ ] Create grid view for contracts based on the designs provided
 - [x] Create option to users for switching between grid view and tabular view
 - [ ] Pagination, filters, search etc should work appropriately
 - [ ] Add or modify any tests appropriately

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Please reach out to the core team for any clarifications regading this issue.

**Comment by pelsasser** [comment]
Some notes!

- We are working on implementing a standarized contract naming scheme, which will help to populate the two names needed that are currently represented by EOS : ETH (reference asset : collateral token)
  - the function `parseStandardizedContractName` will parse the contract name to return the needed pieces returns an object that looks like 
```
    return {
      referenceAsset: splitName[0],
      collateralToken: splitName[1],
      dataProvider: splitName[2],
      expirationTimeStamp: expiration,
      userText: splitName.length > 4 ? splitName[4] : '' // user text could be optional
    };
```

**Comment by pelsasser** [comment]
@mikestonecodes is gonna take this one on

**Comment by pelsasser** [comment]
@mikestonecodes - please let us know a timeline for completion on this when you can.

Thanks!

**Comment by pelsasser** [comment]
@mikestonecodes - any progress here? if your too busy, no problem, just let us know.

**Comment by mikestonecodes** [comment]
Hey @pelsasser I am starting now. Sorry about the delay.

**Comment by mikestonecodes** [comment]
I can complete by Tuesday, hopefully earlier. Sorry I missed your messages.

**Comment by pelsasser** [comment]
thanks @mikestonecodes - looking forward to it!
