### ISSUE TITLE
[Deploy Contracts] Improve deploy contracts step UX

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#277]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to know the things going on underneath while the contracts are being deployed. Ability to view the transaction hash for each step, getting to know where the contracts have failed (in case of failure) would help me understand the deploy contracts process better. 

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Right now we have a simple UI for the deploy contract flow which is sufficient. Adding more UX details to it should perfect it. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
1 - User is not able to click on `Deploy Contract` once the process moves to `Deploy Collateral Pool & Link Contract` to view the transaction hash
<img width="532" alt="screen shot 2018-07-30 at 10 50 38 pm" src="https://user-images.githubusercontent.com/4952395/43412880-1ef6c4ce-944c-11e8-9494-a1c0ea5f122e.png">

2 - In this example, the process failed in first step, appropriate `failure` icons should be shown on each steps in case of failure insted of showing the 'check' mark as step icon which is misleading.
<img width="537" alt="screen shot 2018-07-30 at 10 52 13 pm" src="https://user-images.githubusercontent.com/4952395/43412980-5ddf0516-944c-11e8-829b-fc1cdec1095c.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
1 - 
<img width="532" alt="screen shot 2018-07-30 at 10 50 38 pm copy" src="https://user-images.githubusercontent.com/4952395/43414894-b563aa76-9451-11e8-838c-7599e5aaf7f7.png">

2 -
<img width="537" alt="screen shot 2018-07-30 at 10 52 13 pm copy" src="https://user-images.githubusercontent.com/4952395/43415007-10f782a4-9452-11e8-9a8f-9d7bc658f65f.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Try to deploy contracts via any method

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] User should be able to navigate between the steps to see the completed transaction hash and description etc. 
- [ ] User should be able to view in which step the deployoment process failed in case of failure

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Please contact the core team in case of any issues or clarifications needed.

**Comment by KennethAshley** [comment]
@nitinrgupta I think ill try and tackle this. Am i correct in assuming that the icon below is a spinning icon that indicates progress? 

![image](https://user-images.githubusercontent.com/1138619/43425233-f26fcac6-941f-11e8-9cf4-fea46ebdda43.png)

**Comment by nitinrgupta** [comment]
Yes @KennethAshley. This state is when the user clicks on the previous step if the 'Deploy collateral pool & link contract' step is still in progress.

**Comment by rojosnow** [comment]
@KennethAshley How are you doing here?

**Comment by KennethAshley** [comment]
@rojosnow This slipped past me. Sorry. A few things came up right after taking this issue which needed my time. Sorry for not updating you guys. I can work on it now but i will understand if you would like someone else to take it!

**Comment by KennethAshley** [comment]
@rojosnow @nitinrgupta I'll have this done EOD. Again i apologize for the delay.

**Comment by KennethAshley** [comment]
@nitinrgupta any suggestions on how you want to see errors? If you take a look at [Error Status](https://ant.design/components/steps/) you can see that there is a step with a red line. I can do something like that if you want.

**Comment by eswarasai** [comment]
@nitinrgupta -- Can you please respond to @KennethAshley's query?

**Comment by nitinrgupta** [comment]
@KennethAshley go ahead with that :)

**Comment by KennethAshley** [comment]
Sweet! I'll get this done!
