### ISSUE TITLE
Refactor dApp usage of getTokenBalance to use new MARKET.js function getBalanceAsync

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/dApp#296]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Continuous improvements, this functionality was exposed in MARKET.js 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Maintenance 
We need to update the usage of utils `getTokenBalance`.

### Current Behavior
[comment]: # (Describe what actually happened.)
util/utils.js `getTokenBalance`

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
use the instantiated market.js in the store to and the newly exposed `getBalanceAsync` function.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] All instances of getTokenBalance have been replaced with getBalanceAsync
- [ ] getTokenBalance is removed from util/utils.js

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
If you have any questions please contact @travisdmathis or @eswarasai

**Comment by perfectmak** [comment]
@travisdmathis, looking at this issue now. Wouldn't it be dependent the next release of the MarketJS library?

**Comment by travisdmathis** [comment]
@perfectmak yes, it would.

**Comment by perfectmak** [comment]
Okay, so we wait till the next MarketJS release.

**Comment by perfectmak** [comment]
@travisdmathis can I still do this or you've got this?

**Comment by travisdmathis** [comment]
@perfectmak feel free to take it, i have some other priorities i have to get to..

**Comment by perfectmak** [comment]
@travisdmathis I submitted a PR for this. Kindly take a look when chanced.

Some extra things I did was to upgrade marketjs to 0.3.0 and also rename getUserAccountBalanceAsync() to the new getUserUnallocatedCollateralBalanceAsync().
