### ISSUE TITLE
[UI/UX] Handle long numerical digits in Sim exchange wallet

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#310]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Wallet amount which exceeds certain decimal digits is looking weird right now. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
![walletdatatolong](https://user-images.githubusercontent.com/4952395/44591531-97210480-a7db-11e8-8cb0-71bfaf2df24f.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Fix the current behavior by figuring out a proper solution to it.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Long wallet amount should not break to next line

**Comment by pelsasser** [comment]
I think 5 decimals is probably reasonable, if that is too long from a design perspective, we could do less.

**Comment by travisdmathis** [comment]
@pelsasser @nitinrgupta what if in the view we round off to X digits and then if you hover over the value it shows a tooltip/popup w/ the 18 digit amount?

**Comment by pelsasser** [comment]
this sounds cool

**Comment by CosmicCoder96** [comment]
@nitinrgupta Are you working on this, or is it available to work on?

**Comment by nitinrgupta** [comment]
@CosmicCoder96 I've started work on this already :(

Check out this issue: https://github.com/MARKETProtocol/dApp/issues/328 which is fairly simple to tackle at the moment. We'll be having bunch of other issues filed soon.

**Comment by CosmicCoder96** [comment]
@nitinrgupta sure, thanks!
