### ISSUE TITLE
Update tooltips with relevant text in Sim exchange

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#315]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Add proper texts for the following tooltips in Sim exchange:
- Available Collateral
- Available for Trading
- Order Book
- Trade Charts
- Open Orders
- Positions
- Fills
- Trade History

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Tooltips contains appropriate helpful information

**Comment by nitinrgupta** [comment]
@pelsasser can you suggests some appropriate text for these tooltips?

**Comment by pelsasser** [comment]
Yes!

Can you clarify -
Available Collateral - this is the users wallet balance?
Available for Trading - this is the balance the user has deposited into the specific contract?

**Comment by nitinrgupta** [comment]
Yes @plessaser

**Comment by pelsasser** [comment]
- Available Collateral 
  - rename to Available to Deposit?
  - `This is the amount in your wallet that is currently available to deposit into the selected MARKET Protocol Smart Contract`
- Available for Trading
  - rename to Available To Trade?
  - `This is the amount of collateral you have available with to trade with in the selected MARKET Protocol Smart Contract`
- Order Book
  - `The Order Book displays all orders that are currently open and able to be filled`
- Trade Charts
  - `These charts help to visualize the current state of the market and the depth of orders.`
- Open Orders
  - `All orders for the currently selected  MARKET Protocol Smart Contract that have been generated by you and are currently available to be filled are listed here`
- Positions
  - `All of your open positions for the selected MARKET Protocol Smart Contract are displayed here`
- Fills
  - `All transactions for the selected MARKET Protocol Smart Contract that you have been involved with as either the maker or taker, are shown here.` 
- Trade History
  - `All transactions for the selected MARKET Protocol Smart Contract are shown here.`

**Comment by CosmicCoder96** [comment]
@nitinrgupta @pelsasser I would like to work on this.

**Comment by nitinrgupta** [comment]
I was about to open up a PR 😅 But go ahead, I haven't worked on this yet 😄

**Comment by CosmicCoder96** [comment]
@nitinrgupta 😅 okay

**Comment by pelsasser** [comment]
@CosmicCoder96 - thanks for all the help!! Have you joined our [discord](https://marketprotocol.io/discord) yet?!

**Comment by CosmicCoder96** [comment]
@pelsasser Thanks! I just did (AbhinavKhare)
