### ISSUE TITLE
Contract dropdown responsive issues

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/dApp#328]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description
When viewing the new exchange ui the contract dropdown breaks on certain views

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 

### Current Behavior
[comment]: # (Describe what actually happened.)
around 1200px the contract dropdown collapses

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
it should be visible and clickable

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Bug is fixed and dropdown is visible in all views

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
![brokendropdown](https://user-images.githubusercontent.com/1335198/44672365-39b4cf80-a9f6-11e8-8352-15974832e379.png)

**Comment by CosmicCoder96** [comment]
I am working on this.
