### ISSUE TITLE
Deprecate the usage of getWhitelistedContracts end point

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/dApp#332]
### Why Is this Needed?
The end point is being deprecated.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

We are deprecating the getWhitelistedContracts end point in favor for the new contracts endpoint w/ filters.  We need to update all instances in the dApp.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [x] Contract Explorer and Contract Dropdown Widget should use contracts endpoint with whitelisted filter to retrieve available contracts.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by perfectmak** [comment]
@travisdmathis, Also while tackling this, is it okay to remove the caches setup too. Since we would be fetching from the API now?
