### ISSUE TITLE
Fix contract selection dropdown in Sim exchange

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#334]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I need to select different contracts to trade on in the sim exchange easily. A drop down to choose from the different contacts could do.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Right now, the contract selection dropdown is a mess. Modify the dropdown to have a contract search input and a scrollable area

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="505" alt="screen shot 2018-08-29 at 7 15 54 pm" src="https://user-images.githubusercontent.com/4952395/44795311-fe69fa80-abc7-11e8-8210-8aee648f6ed6.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
<img width="1032" alt="screen shot 2018-08-29 at 8 14 35 pm" src="https://user-images.githubusercontent.com/4952395/44795390-2f4a2f80-abc8-11e8-8dfd-66c32795126a.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Go to `/exchange` in the dApp. Click on the contract in the sim exchange topbar to trigger the selection dropdown

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
See if AntD's [popover](https://ant.design/components/popover/) would be an ideal usage for the proposed design. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Modify the contract selection dropwdown with the proposed design
- [ ] Complete search functionality in the updated contract selection
- [ ] Add or update tests accordingly

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Please refer to the zeplin screen for UI specifications: https://app.zeplin.io/project/5b06ec51910686b53d883851/screen/5b86b1903807c116ecd03399

React out to the core team on [Discord](https://discordapp.com/invite/qN8MCbq) for any queries

**Comment by pelsasser** [comment]
@CosmicCoder96 - can you confirm your working on this? if so I will put the appropiate labels on it! thanks!

**Comment by CosmicCoder96** [comment]
@pelsasser yes I am working on it :)

**Comment by eswarasai** [comment]
@CosmicCoder96 -- Can you update the status on this? It'd be great if you can create a WIP PR. Let us know if you need any help from us. Thanks!

**Comment by CosmicCoder96** [comment]
@nitinrgupta @eswarasai Apologie for the delay, I had to travel urgently mid-work. I had used ant design's [Select with search](https://ant.design/components/select/) to fix it as it includes a search bar by default. I am returning today evening and will send a PR by end of today. On a flight right now.
