### ISSUE TITLE
[Sim exchange] Implement positions section

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#352]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Implement the positions section table in the sim exchange based on the design

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI Enhancement

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
The positions should appear based on the following design
<img width="563" alt="screen shot 2018-09-11 at 7 22 09 pm" src="https://user-images.githubusercontent.com/4952395/45364541-08dcb900-b5f8-11e8-9db0-1c32759944c3.png">

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Zeplin URL : https://zpl.io/29yQj9z

**Comment by perfectmak** [comment]
@nitinrgupta is there anything blocking this? Can I work on it?

**Comment by nitinrgupta** [comment]
@perfectmak there's nothing blocking as such. Feel free to go ahead and work on this :)

But I wanted to envision the UI before getting into the implementation. 
So, here's a simple mock which I'm thinking. 
<img width="513" alt="screen shot 2018-09-11 at 12 34 45 pm" src="https://user-images.githubusercontent.com/4952395/45343686-39ecc780-b5bf-11e8-8257-bcaadb3464a3.png">
You can ignore the `ETH` symbol implementation for now. We'll have to do that across the sim exchange later on using some library.

@pelsasser would be happy to know your comments on the above mock for the positions section and see if I've missed out on something or not :)

**Comment by pelsasser** [comment]
Can we add color in?  So long positions (which are + qtys) would match our buy color, and the short positions (which are negative) would match the sell color.

Also, not needed, but may help is the same arrows we used in the collateral screen.

**Comment by nitinrgupta** [comment]
@perfectmak UI is locked down and updated on the issue description. Feel free to work on this whenever you can :)

**Comment by perfectmak** [comment]
Okay @nitinrgupta, I'll begin work on this asap. I'll sync with you on discord is any questions arise.
