### ISSUE TITLE
[Sim exchange] Implement trade history section

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#353]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Implement the trade history table UI based on the desing

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI Enhancement

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
<img width="334" alt="screen shot 2018-09-10 at 12 40 12 pm" src="https://user-images.githubusercontent.com/4952395/45281835-af409580-b4f6-11e8-90c4-85831d2db92a.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Implement the UI based on the above design

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by eswarasai** [comment]
@pelsasser -- I have couple of questions related to the task. Please find them below :

 - The values beside Qty and Price, are they `symbolName` and `quoteAsset` of the Contract Name?
 - In the below sample `getContractFillsAsync()` result, I couldn't find the time of filled event to be displayed. Should I go ahead and open an issue in `MARKET.js` to add timestamp to the fill order events?

```
{
    "maker": "0xce5fdef0592271c41c4ac07ddb52ae3bbb3fcb9e",
    "taker": "0x102b556d0c5f93d056f0fe00dab8d7da54942026",
    "feeRecipient": "0x0000000000000000000000000000000000000000",
    "filledQty": "1",
    "paidMakerFee": "0",
    "paidTakerFee": "0",
    "price": "5500",
    "orderHash": "0xed02591a51375f4ffe1f3682a2ec95ffee24d830de50be5d50b6cbe165310dc7",
    "blockNumber": 2971020,
    "txHash": "0xc437d6eee003b8bde604822097112db21ce1e212b665b1b5063da27bc32685b4"
}
```

@nitinrgupta -- What do the different colors depict for Price? Are they buy/sell orders or the price up/down based on the caret beside? Not sure what's the logic behind this. If you and @pelsasser can shed some light on how it needs to be implemented, I'll get on with it. Thanks!

**Comment by nitinrgupta** [comment]
@eswarasai the primary color (teal) depicts a buy order and the secondary color (orange) depicts the sell order

**Comment by eswarasai** [comment]
@nitinrgupta -- What's the caret depicting beside the price then?

@pelsasser -- Am I right to understand that if the `filledQty` in the above JSON result is positive, it's a buy order and if it's negative it's a sell order or do we need to add another key to distinguish between the buy/sell orders?

**Comment by nitinrgupta** [comment]
@eswarasai the caret depicts the buy and sell orders.

**Comment by pelsasser** [comment]
@eswarasai - 

> In the below sample getContractFillsAsync() result, I couldn't find the time of filled event to be displayed. Should I go ahead and open an issue in MARKET.js to add timestamp to the fill order events?

that would be great!

> Am I right to understand that if the filledQty in the above JSON result is positive, it's a buy order and if it's negative it's a sell order or do we need to add another key to distinguish between the buy/sell orders?

Yes! + for buy, - for sell
