### ISSUE TITLE
[UI/UX] Implement buy/sell order flow from order book

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#366]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Implement the flow where user can fill an order using the order book using the UI designed

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Designs posted in #354

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Implement based on the given UI
- [ ] Add required tests

**Comment by perfectmak** [comment]
@nitinrgupta is this open? I would like to work on this

**Comment by nitinrgupta** [comment]
@perfectmak - yes this is open. Feel free to knock this out :)
