### ISSUE TITLE
[UI/UX] Add collateral type in column headers

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#389]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I'd like to know which type of collateral I'm looking at in the columns of Trade History, Order book etc

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Add appropriate collateral type next to the name of the column header which would be a better experience for the users.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="270" alt="screen shot 2018-09-24 at 6 54 11 pm" src="https://user-images.githubusercontent.com/4952395/45954682-45160d80-c02b-11e8-8f12-4a89cac37046.png">
<img width="255" alt="screen shot 2018-09-24 at 6 54 06 pm" src="https://user-images.githubusercontent.com/4952395/45954692-4c3d1b80-c02b-11e8-934b-cef0a24d9c00.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Similar to that of Positions section column headers
<img width="463" alt="screen shot 2018-09-24 at 6 56 50 pm" src="https://user-images.githubusercontent.com/4952395/45954801-9de5a600-c02b-11e8-9643-eaa17bb7cba1.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Navigate to `/exchange` 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Add collateral type similar to that of implemented in Positions section

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Add the collateral type to Order Book, Trade History, Wallet History, Buy and Sell section and wherever necessary
- [ ] Add or modify tests accordingly

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
reach out to @travisdmathis, @nitinrgupta, or @eswarasai for any additional information.

**Comment by pelsasser** [comment]
@nitinrgupta - would it be better to have the contract name or perhaps just the part of the contract name?

I am not sure it make sense to just the collateral token there.

for instance, if the contract we are trading is BTCUSDT, what I probably care about is knowing exactly that.  BTC alone (or USDT alone) isn't all that helpful I think.

**Comment by nitinrgupta** [comment]
@pelsasser where exactly are you referring to add the contract name or part of the contract name?

Wouldn't it be helpfull for users to understand in what Collateral token the Qty is if we have `Qty(ETH)` as a column header instead of just `Qty`? The same goes to the `Price` and `My Qty` column

**Comment by nitinrgupta** [comment]
Decided to remove the collateral token on `Qty` for time being over the Dev call to avoid the confusion w.r.t contracts being traded and not the actual collateral token. 
cc: @eswarasai @pelsasser

**Comment by pelsasser** [comment]
:+1:

**Comment by eswarasai** [comment]
@nitinrgupta -- Updated the PR. Feel free to review and comment on any other changes required. Thanks!
