### ISSUE TITLE
[BUG] My FillsOrdersPositions height needs to be set to 100%

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/dApp#413]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

We're not maximizing the available height of the widget for displaying data.. currently is getting cut off at the bottom. Setting #order-positions-fills > .antd-tabs height to 100% will fix the issue.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by travisdmathis** [comment]
@nitinrgupta develop, i have a bunch of positions on the BTC_USDT contract and it gets cut off with about 150px left in the component height.. i did some fiddling in the inspector and got it to work right.

**Comment by nitinrgupta** [comment]
@travisdmathis I think I've handled it in my latest PR merge. Let me know if you still see the same issue
