### ISSUE TITLE
[BUG] My OrdersPositionsFills should account for maker/taker in display direction/color

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/dApp#414]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

Currently these components are only accounting for wether or not the order is + or - quantity.  We need to also look at wether or not the user is the maker or taker to determine the correct display direction dynamically.

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by pelsasser** [comment]
@eswarasai - any status on this #413 ?
