### ISSUE TITLE
Unable to deploy a contract with Quick deployer and MetaMask

### ISSUE THREAD

**Issue by cryptomental** [MARKETProtocol/Dapp#58]
I was struggling a lot to get this working, lost >2h hours and I am kind of stuck.

1) Gas limit was recently increased to 6500000 . This is fine for initial deployment script but MetaMask maximum value is 6385876 . Deploy transactions fail with out of gas.

2) I often got {type: "DEPLOY_CONTRACT_REJECTED", payload: {…}}
payload : {error: "Web3 not initialised"} error, although MetaMask was unlocked. This worked fine until recently, I remember that there were some changes around this area. I tried to restart truffle and bridge, do fresh a migration but ended up twice with reinstalling MetaMask.

3) I had issues with MetaMask complaining about nonce (see below) and had to implement additional code that checks nonce right before sending deploy tx.

```
[
            {
              "op": "add",
              "path": "/err",
              "value": {
                "message": "Error: Specified nonce may not be larger than account's next valid nonce.",
                "stack": "Error: Specified nonce may not be larger than account's next valid nonce.\n    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:40710)\n    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:957495)\n    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:957283)\n    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:957674)\n    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:264337)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:264433\n    at <anonymous>"
              }
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "failed",
              "note": "txStateManager: setting status to failed"
            }
          ]
```
All this blocks me with solving https://github.com/MARKETProtocol/Dapp/issues/37.

The contract that I wanted to deploy using quick deployer is rather a simple one: 

http://localhost:3000/contract/deploy?mode=quick&contractName=ETHEUR&priceFloor=9000&priceCap=10000&priceDecimalPlaces=1&qtyMultiplier=1&oracleDataSource=URL&oracleQueryRepeatSeconds=60&oracleQuery=json(https://api.gdax.com/products/BTC-EUR/ticker).price&baseTokenAddress=0xf204a4ef082f5c04bb89f7d5e6568b796096735a

@perfectmak  @eswarasai @KennethAshley @pelsasser I would be grateful if you could have a look yourself, try to deploy several contracts with quick deployer and double check if this happens for you as well. Perhaps I am doing something wrong.

**Comment by perfectmak** [comment]
Which network is your meta mask extension connected to? Have you set to
work with the local test network.

**Comment by cryptomental** [comment]
hi @perfectmak I use localhost:9545 network started with 'truffle develop' . My MetaMask is connected to the private network. I also sent 1 ETH to my MetaMask address on the private network to try things out.

**Comment by cryptomental** [comment]
Before I used truffle console, now I added web3.eth.sendTransaction({from:web3.eth.coinbase, to: '0xmy_metamask_address', value: web3.toWei(1, "ether") }) to 2_deploy_contracts.js so that I always get ETH right after all migrations.

**Comment by pelsasser** [comment]
I can take a look at this soon.  We are going to remove several of the funding checks and move them off chain which will reduce the costs of deployment significantly.  That is being worked on now in the dApp.

**Comment by eswarasai** [comment]
@cryptomental -- And also it might be a better idea to use `Ganache-cli` and connect the Metamask to the same local network `http:localhost:9545` going forward. Thanks.

**Comment by cryptomental** [comment]
@eswarasai that's interesting , I thought 'truffle develop' uses ganache-cli under the hood.

My usual Dapp start flow during development  is the same as defined in travis.yml  

1. truffle develop
2. start eth-bridge, wait until Oraclize connector fully initializes
3. truffle migrate
4. npm run start

For me Dapp starts automatically in chrome, with MetaMask set to connect to localhost:9545

If I understood correctly you start ganache-cli in step 1) , is there anything else different in how you start the Dapp? Do you log out in MetaMask before starting the Dapp?

**Comment by eswarasai** [comment]
@cryptomental -- I meant using the Desktop application of [Ganache](http://truffleframework.com/ganache/)

I'm not sure about Docker but here are the steps that I use to run the server locally
1. Start Ganache App
2. Start `ethereum-bridge` and wait until Oraclize connector fully initialises
3. `truffle migrate`
4. `npm start`

W.r.t. Metamask, you can connect it to Custom RPC `localhost:9545` and import one of the Accounts from the `Ganache`. Let me know if you need any help with this.

**Comment by cryptomental** [comment]
Thanks a lot @eswarasai !

**Comment by pelsasser** [comment]
@cryptomental - I am going to stake an issue over on the protocol side to remove all of the checks for sufficient funding.  We can do those in the dApp and move that off chain.  If you want to pick it up, I will try and get it staked in a few

**Comment by pelsasser** [comment]
resolved @cryptomental please double check.

**Comment by cryptomental** [comment]
Thanks @pelsasser ! from what I see during migration on 0.0.14 gas consumed dropped ~400000 gas for the largest contract which makes it now 6004692. This is good. I will now try to deploy a contract using Quick Deployer on Dapp master + 0.0.14 release.

**Comment by cryptomental** [comment]
![image](https://user-images.githubusercontent.com/20819151/37090136-6dba55be-2203-11e8-98a8-9e1575bad4f4.png)

Setting as resolved! Thanks @pelsasser

**Comment by pelsasser** [comment]
@cryptomental - awesome!  I have some grand ideas for getting the gas quite a bit lower - lets connect on it soon
