### ISSUE TITLE
[Find Contract] Modify the UI to display Contract info

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/dApp#60]
Display the Contract info in a nice vertical tabular format as opposed to the below one.

<img width="1680" alt="find contract ui" src="https://user-images.githubusercontent.com/5172086/38420154-7d66223e-39c0-11e8-94a4-b82e1b183cdd.png">

**Comment by pelsasser** [comment]
@eswarasai - can you add some clarity to this issue and I can get some ETH attached to get it worked on?

**Comment by pelsasser** [comment]
@eswarasai - please update ;)

**Comment by rojosnow** [comment]
@pelsasser @eswarasai I've got a job candidate interested in working this issue. Is it still valid given the other UI work we're doing?

**Comment by eswarasai** [comment]
@rojosnow -- This issue is currently in Backlog. Sorry for the confusion. Just updated the status. Feel free to ask the person to help us with #153 maybe. Thanks :)

**Comment by nitinrgupta** [comment]
@eswarasai I think this issue can be closed since the new design on the explorer page combines this functionality.

**Comment by eswarasai** [comment]
Ref: https://github.com/MARKETProtocol/dApp/issues/227
