### ISSUE TITLE
[Welcome Screen] Issues with graphics when sizing window to be narrower

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/Dapp#63]
![screenshot from 2018-03-10 16-54-33](https://user-images.githubusercontent.com/15096737/37240239-da480f28-2483-11e8-9462-654560f6a52a.png)

**Comment by pelsasser** [comment]
@nitinrgupta

**Comment by nitinrgupta** [comment]
Haven't handled the responsiveness yet. Will be doing it eventually.

**Comment by pelsasser** [comment]
@nitinrgupta sounds good - just had put this out to a few people and wanted to make sure we address some of the things that came back.

**Comment by nitinrgupta** [comment]
Done. Created a PR for this.
