### ISSUE TITLE
[Test Query] Issue with animation overlay when test query submitted

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/Dapp#64]
![screenshot from 2018-03-10 16-58-02](https://user-images.githubusercontent.com/15096737/37240288-3843dd6e-2484-11e8-976c-7dc82c0aa163.png)

**Comment by pelsasser** [comment]
@nitinrgupta

**Comment by nitinrgupta** [comment]
@eswarasai I had another solution for this. Created a PR for that. I feel that would be a better way of handling the loader position in the page.

**Comment by pelsasser** [comment]
This looks good @nitinrgupta and @eswarasai !!!
