### ISSUE TITLE
Create functionality to allow users to copy specifications from already deployed contracts

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#8]
The deploy contracts page will have several fields that can be re-used between similar contracts.  We could create functionality that would allow easy re-deployment of contracts with modified specs.

- quick click to created longer dated expiration
- ability to create new range (`PRICE_CAP` and `PRICE_FLOOR`) based on current oracle pricing

**Comment by pelsasser** [comment]
This could be as simple as selecting a deployed contract in the explorer and hitting a button that says `copy specifications to deployer` or a right click drop down with something similiar

**Comment by eswarasai** [comment]
@pelsasser -- What's the priority of this? I think this should be easy to do since now we support deploy contract values being passed as URL params right.

**Comment by pelsasser** [comment]
@eswarasai - low.  Feature for after we get current dApp deployed publicly.
