### ISSUE TITLE
[explorer] missing error handling around invalid contract addresses

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#80]
![image](https://user-images.githubusercontent.com/15096737/37775634-69bff276-2e1e-11e8-9cfc-7ec2ebbcf4da.png)

If a contract is deployed with an invalid erc20 address (which we should not allow upstream, but still handle issues downstream) the explorer fails to load

**Comment by maektwain** [comment]
Yeah this should be resolved in the upcoming  PR  #78  though @pelsasser suggest that we can use validation here.

Thanks

**Comment by eswarasai** [comment]
@pelsasser -- I'm aware of this issue. Since there shouldn't be such invalid contract address in the first place, I've prioritised adding validation to contract address while deploying contracts, rather than fixing things in the explorer. Let me know if you'd like to have it otherwise. Thanks.

**Comment by pelsasser** [comment]
I think we should tackle it from both sides, eventually.  Having the explorer crash due to insufficient error handling doesn't seem beneficial even if we think that it shouldn't ever happen

**Comment by eswarasai** [comment]
@pelsasser -- Makes sense. I forgot about the scenario of contract not existing at the given address anymore.

@maektwain -- Can you please handle the same in `actions/explorer.js`? Thanks.

**Comment by maektwain** [comment]
Yeah sure would add the validations here 

1. Yeah eventually we should have some kind of global validations on the form which basically do a check before submitting form.
