### ISSUE TITLE
Insufficient balance error is quite big 

### ISSUE THREAD

**Issue by maektwain** [MARKETProtocol/Dapp#82]
When testing query using orcalize on Rinkeby testnet shows big error which can confuse user.

``
Error: Error: [ethjs-rpc] rpc error with payload {"id":9522477269349,"jsonrpc":"2.0","params":["0xf9013080843b9aca0083030d4094dcc2435435c81cadb1944ff569a8a8d94473e1b2871550f7dca70000b8c4416851a000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000c576f6c6672616d416c7068610000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4141504c205052494345000000000000000000000000000000000000000000002ca090ecb19dba3ee35d8c5ac3b2cd2359724ae4a4d93974cf6460f49d792c49941ba07bedb8e462f6345f50aedcdb93e54ecc674e8c5b7432b3d518eb13ef97724b6c"],"method":"eth_sendRawTransaction"} Error: insufficient funds for gas * price + value at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:38080) at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:583428) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:584992 at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:585062) at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89967) at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89569) at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:41649) at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652) at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440) at Generator.e.(anonymous function) [as throw] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390977
``

Instead we can show : 

"Hey , sorry you do not have enough balance"

**Comment by cryptomental** [comment]
This is interesting... In this scenario I see MetaMask notification with "Insufficient balance for transaction" error message:

![screenshot from 2018-03-27 14 48 29](https://user-images.githubusercontent.com/20819151/37968332-1bd3d9fc-31ce-11e8-8c94-6697af1ec31a.png)

@maektwain  could you please provide exact steps, including workspace setup and your configuration changes that led to this issue? Thanks.

**Comment by cryptomental** [comment]
I tested this as well on Rinkeby and the [deployed Dapp](http://52.90.115.134:3000/test)

![screenshot from 2018-03-28 12 05 15](https://user-images.githubusercontent.com/20819151/38022704-88fbdac2-3280-11e8-91f9-d41600a70f70.png)

@pelsasser @maektwain could you please share how you were able to reproduce this problem?

**Comment by cryptomental** [comment]
I think that I start to understand now... I could not reproduce the exact scenario, but after pressing 'REJECT' button, the message also does not fit the screen.

**Comment by maektwain** [comment]
Ok, Here are the steps 

Step 1.
<img width="393" alt="screen shot 2018-03-28 at 4 46 50 pm" src="https://user-images.githubusercontent.com/8274610/38025897-afee51d8-32a7-11e8-9369-a7a86d713183.png">
Step 2.

The moment I cancel 

<img width="1172" alt="screen shot 2018-03-28 at 4 46 21 pm" src="https://user-images.githubusercontent.com/8274610/38025901-b4083b6c-32a7-11e8-8ee4-64fcde5be1ee.png">

Step 3 When confirm in case of insufficient balance 
 
<img width="1198" alt="screen shot 2018-03-28 at 4 48 51 pm" src="https://user-images.githubusercontent.com/8274610/38025966-ea7d24dc-32a7-11e8-851b-84bdff25315f.png">

Thanks

**Comment by cryptomental** [comment]
Ok, thanks @maektwain ! I have a fix and will submit it in a few minutes.

**Comment by cryptomental** [comment]
Pull request opened https://github.com/MARKETProtocol/Dapp/pull/83
