### ISSUE TITLE
Configure web3 provider for unit test cases

### ISSUE THREAD

**Issue by saralarambhapuri** [MARKETProtocol/dApp#94]
Currently, in the tests, for the actions, we're not able to get the `coinbase` account as we're using FakeHttpProvider. In order to get the functional tests covered for features like deployed contracts etc, we need to have a `testnet`, for example Rinkeby, where the necessary contracts are deployed before performing the functional tests and also using the same `testnet` to be configured in `web3` along with the `coinbase` account, which can be used to perform the necessary calls/transactions.

**Comment by eswarasai** [comment]
Will be using truffle/ganache as web3 provider for test cases as well
